### PR TITLE
yet another towards CRAN

### PR DESCRIPTION
**Pull request by urbach**

### CODE REVIEW

**Comment by urbach** [comment]
> martin-ueding approved this pull request.

more to come...

> 
> 
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HISKP-LQCD/hadron/pull/240#pullrequestreview-343909998
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by urbach** [comment]
we still have

       cvc_read_loops: no visible global function definition for ‘H5Fclose’
       Undefined global functions or variables:
         H5Fclose h5ls 

importFrom, but not a CRAN package?

**Comment by martin-ueding** [comment]
`importFrom` should not care where the package comes from. Once it is installed we can load it. So I would say we can just load the needed functions as usual.

**Comment by urbach** [comment]
where did they come from again?

**Comment by kostrzewa** [comment]
> where did they come from again?

That's my fault. While I had all the proper namespaces in `cyprus_readutils`, I had forgotten to add these to the corresponding `cvc_readutils` for my CVC loop format.

**Comment by martin-ueding** [comment]
`rhdf5` is the package name.

**Comment by urbach** [comment]
does someone understand this warning?

       Found the following apparent S3 methods exported but not registered:
         plot.outputdata plot.uwerr
       See section ‘Registering S3 methods’ in the ‘Writing R Extensions’
       manual.

**Comment by kostrzewa** [comment]
My guess would be that `plot.outputdata` and `plot.uwerr` functions don't have the same signature as the `plot` generic.

**Comment by urbach** [comment]
> `rhdf5` is the package name.

So, I guess

#' @importFrom rhdf5 h5ls H5Fclose

should do the job...?

**Comment by urbach** [comment]
> My guess would be that `plot.outputdata` and `plot.uwerr` functions don't have the same signature as the `plot` generic.

no, I think it does...

**Comment by urbach** [comment]
one need to replace

    #' @export plot.uwerr

with

    #' @export

**Comment by urbach** [comment]
argh, I have an old version of `rhdf5` for an old R version. How was that updated again?

**Comment by kostrzewa** [comment]
> argh, I have an old version of rhdf5 for an old R version. How was that updated again?

which one of the three ways would you like?

**Comment by urbach** [comment]
I think I found one already... thanks

**Comment by urbach** [comment]
... waiting for rhdf5 ...

**Comment by urbach** [comment]
hmm, if this now need `rhdf5` for the check, it will not work with CRAN, will it?

**Comment by urbach** [comment]
okay, seems `@importFrom rhdf5 ...` is not needed...

**Comment by kostrzewa** [comment]
> hmm, if this now need rhdf5 for the check, it will not work with CRAN, will it?

While one should check, I seem to remember that depending on non-CRAN via `Suggests` is fine... "Writing R Extensions" is a bit vague on this...

**Comment by urbach** [comment]
do we need these flags?

      Compilation used the following non-portable flag(s):
        ‘-Wno-macro-redefined’ ‘-Wno-unused-function’
        ‘-Wno-unused-local-typedefs’ ‘-Wno-unused-variable’ ‘-march=native’
      including flag(s) suppressing warnings

**Comment by urbach** [comment]
> > hmm, if this now need rhdf5 for the check, it will not work with CRAN, will it?
> 
> While one should check, I seem to remember that depending on non-CRAN via `Suggests` is fine... "Writing R Extensions" is a bit vague on this...

it explicitly complains if I @importFrom rhdf5...

**Comment by kostrzewa** [comment]
> it explicitly complains if I @importFrom rhdf5...

I see, that's nice...

**Comment by urbach** [comment]
> do we need these flags?
> 
> ```
>   Compilation used the following non-portable flag(s):
>     ‘-Wno-macro-redefined’ ‘-Wno-unused-function’
>     ‘-Wno-unused-local-typedefs’ ‘-Wno-unused-variable’ ‘-march=native’
>   including flag(s) suppressing warnings
> ```

where do we set these in the first place?

**Comment by martin-ueding** [comment]
https://cran.r-project.org/web/packages/policies.html says this:

> Packages on which a CRAN package depends should be available from a mainstream repository: if any mentioned in ‘Suggests’ or ‘Enhances’ fields are not from such a repository, where to obtain them at a repository should be specified in an ‘Additional_repositories’ field of the DESCRIPTION file (as a comma-separated list of repository URLs) or for other means of access, described in the ‘Description’ field. 

I think I asked about this at some point, and BioConductor is a *mainstream repository* for this purpose. So we should be fine with `rhdf5`.

**Comment by urbach** [comment]
I think this could be merged in now...!

**Pull request merged**
