### PR TITLE
Eigenvalue sorting for t < t₀ (Issue #156)

### LINKED ISSUE #156: Eigenvalue sorting in GEVP wrong below t0
for t < t0 we have to reverse the sorting order, I think this is currently not done.

This might explain why principal correllator plots look as they do and also, why the pc model is not working as expected.

### PR DESCRIPTION
**Pull request by urbach**
can this be applied to the rho data for a test, please!?

this should provide a fix for #156

### CODE REVIEW

**Comment by urbach** [comment]
could you try again?

**Comment by urbach** [comment]
@martin-ueding could you please review lines 93 to 121 in `gevp.R` carefully? If this is now correct, I think we should check the impact on the rho data!

**Comment by martin-ueding** [comment]
Yes, I'm on the review now.

**Comment by martin-ueding** [comment]
I find this very peculiar:

auswahl_024

At (1) the `evectors` is initialized to be `NA`. And then in (2) it is used as a scalar product. This means that the result is all `NA` and one cannot get an ordering out of that. Is that intentional?

**Comment by martin-ueding** [comment]
In following iterations that might not be a problem, but for the very first iteration it means that there are no reference.

**Comment by urbach** [comment]
> In following iterations that might not be a problem, but for the very first iteration it means that there are no reference.

for `t==t0` always eigenvalue sorting is used, because no eigenvectors
are available... For the next t-value the evectors to compare with
should be available. Does this make sense?

**Comment by martin-ueding** [comment]
Ah! I did not see the *or* clause in the preceeding `if`:

```r
if(sort.type == "values" || t == t0+1) {
```

I will check whether that is consistent now.

Another issue that I saw is that the scalar product is formed between *w* and *v* and not *v* and *v* as described in the documentation.

**Comment by urbach** [comment]
> Another issue that I saw is that the scalar product is formed
> between *w* and *v* and not *v* and *v* as described in the
> documentation.

sorry, which scalar product do you mean?

**Comment by martin-ueding** [comment]
This is the documentation for `gevp`:

docu

The scalar product should be done between the eigenvectors `v`, but in the code it is done between `w` and `v` actually. This is a paragraph from my review (not finished yet):

block

**Comment by urbach** [comment]
okay, I see, well spotted! I have to think about it...

**Comment by martin-ueding** [comment]
I have now finished my review: [gevp_review.pdf](https://github.com/HISKP-LQCD/hadron/files/2891223/gevp_review.pdf)

**Comment by urbach** [comment]
thanks @martin-ueding ! Can we discuss this in person later?

**Pull request merged**
