### PR TITLE
Let uwerrprimary return error on Gamma

### PR DESCRIPTION
**Pull request by martin-ueding**
See Issue #17.

### CODE REVIEW

**Comment by kostrzewa** [comment]
This looks fine, but I don't know why gammaerror depends on Lambda and why ```gamma.err[1]``` is hard-coded

**Comment by kostrzewa** [comment]
Lambda is completely ignored (in the formula in question, it is the maximum lag used to evaluate the variance of the normalised autocorrelation function). The paper states that it is not crucial what the value of Lambda is, but here it seems that W is used instead.

**Comment by urbach** [comment]
okay, `Lambda` is not used indeed and should be removed!

I think using `W` should be sufficient here, shouldn't it?

**Comment by kostrzewa** [comment]
I would agree, yes. I think we can use it as is. I am, however, a bit perplexed as to why the very first error is hardcoded.

**Comment by urbach** [comment]
> I would agree, yes. I think we can use it as is. I am, however, a bit perplexed as to why the very first error is hardcoded.

Well, acutally the error is identically zero, because the value is 1
by construction. But since 0 is not easy to draw, I put a 0.001, not
very elegantly, I agree...

**Comment by kostrzewa** [comment]
I see, this is ready to go in then, I would say.

**Comment by kostrzewa** [comment]
I though the first value was lag '1' rather than lag '0', my bad.

**Pull request merged**
