### PR TITLE
Fix various issues in removeTemporal

### PR DESCRIPTION
**Pull request by martin-ueding**

### CODE REVIEW

**Comment by urbach** [comment]
why does the test still fail?

**Comment by urbach** [comment]
Is this working already with `deltat` not equal to 1?

**Comment by martin-ueding** [comment]
The test now passes locally. I had to modify the sign in the old function (at the top of the file). So please have a look whether you agree with the fix there. Then the new function should be fine because it reproduces the unit tests.

**Comment by martin-ueding** [comment]
I believe that `deltat` ≠ 1 does not work yet, but we are closer to it than before. Could we merge this, such that #193 also advances?

**Pull request merged**
