### PR TITLE
Origin/reweighting

### PR DESCRIPTION
**Pull request by pittlerf**
I would use the functionality provided by icf_support also in this branch

### CODE REVIEW

**Comment by kostrzewa** [comment]
So should the original pull request (#185) be closed?

**Comment by pittlerf** [comment]
> So should the original pull request (#185) be closed?

Yes, I wanted to use the functionality you included, I also tested with just is.null and that did not work.

**Comment by pittlerf** [comment]
thanks:)

**Comment by kostrzewa** [comment]
Ah crap, I didn't see that you were merging the reweighting branch into the isf_support branch

**Comment by kostrzewa** [comment]
I've undone the merge. Please just merge icf_support into the reweighting branch, it makes more sense that way.

**Comment by pittlerf** [comment]
Ok, I have done that.

**Pull request merged**
