### PR TITLE
Further exports

### PR DESCRIPTION
**Pull request by kostrzewa**
some more exports which are required in client code

### CODE REVIEW

**Comment by kostrzewa** [comment]
I bump the version to make the client code aware.

**Comment by martin-ueding** [comment]
I don't get why the unit tests fail for the PR run from these changes. Guess the tests are super flaky because there aren't actually two states of data in there.

**Comment by kostrzewa** [comment]
> I don't get why the unit tests fail for the PR run from these changes. Guess the tests are super flaky because there aren't actually two states of data in there.

Yeah, I have no idea. At first push, it was also only the 'PR' travis run

https://travis-ci.org/HISKP-LQCD/hadron/builds/642865972?utm_source=github_status&utm_medium=notification

which failed while the 'branch' travis run passed just fine...

https://travis-ci.org/HISKP-LQCD/hadron/builds/642865895?utm_source=github_status&utm_medium=notification

I guess the latter does not run all tests though.

**Comment by kostrzewa** [comment]
It must be some problem on Travis as now both test runs have passed (and I basically didn't change anything other than merging #244 via `master`)

**Comment by kostrzewa** [comment]
Travis ...

**Comment by kostrzewa** [comment]
ping

**Pull request merged**
