### PR TITLE
another borderline error which results is unexpected behaviour, this …

### PR DESCRIPTION
**Pull request by kostrzewa**
…time it produces an exponential

### CODE REVIEW

**Comment by kostrzewa** [comment]
```
     expect_equal(tex.catwitherror(0.031921636680, 0.000098, digits = 1, with.dollar=FALSE), '0.0319(1)') 
```

we get: `0.03192(1e-04)` which, while correct, is terrible.

**Comment by martin-ueding** [comment]
I don't think that `0.03192(1e-04)` is correct. We rather want `0.03192(1)`.

**Comment by kostrzewa** [comment]
> I don't think that 0.03192(1e-04) is correct. We rather want 0.03192(1).

I think we rather want `0.0319(1)`, no? We have:

```
val = 0.031922
err = 0.000098
```

which I would expect to be rounded to 

```
val = 0.0319
err = 0.0001
```

to obtain `0.0319(1)`. In that sense I think the `err = 1e-4` that comes out with the present logic is correct, but the scientific notation is clunky and the value should be rounded to the same level as the error was. I don't know how easy it will be to make this happen without destroying wanted behaviour in other edge cases...

**Comment by martin-ueding** [comment]
I messed up the digits. All I wanted to say is that having a scientific exponential in the parentheses makes it incorrect because the overlapping rule of the digits would then lead to an error four orders of magnitude smaller if interpreted strictly.

**Comment by j-ostmeyer** [comment]
Can be fixed by the same change as in #251 .

**Pull request merged**
