### PR TITLE
Add mask to simple.nlsfit

### PR DESCRIPTION
**Pull request by j-ostmeyer**
... and simplify code a bit.

### CODE REVIEW

**Comment by martin-ueding** [comment]
Your pull request comes from your own fork. This means that I cannot push additional commits before merging it. It would be nicer if you just pushed this into a branch in this repository.

**Comment by martin-ueding** [comment]
I have just tried this for my fits with yerrors, some with priors, some without. And they now fail with this (in case of priors):

```
 $ message: chr "the leading minor of order 3 is not positive definite"
 $ call   : language chol.default(CovMatrix)
```

Or that one (not using priors)

```
 $ message: chr "Variance-covariance matrix could not be inverted!"
 $ call   : language inversion.worked(InvCovMatrix)
```

Some fail with the current `master` version, but that is okay since it is due to fit ranges. With your version here it seems that all the fits fail. So there has been some change which breaks `bootstrap.nlsfit` for these cases.

We should add more examples to secure this.

**Comment by j-ostmeyer** [comment]
> $ message: chr "Variance-covariance matrix could not be inverted!"
> $ call   : language inversion.worked(InvCovMatrix)

This looks as if your original Cov-matrix is too badly conditioned and only the one with applied mask can be inverted. So I will move the error calculation back after the mask application.

**Comment by j-ostmeyer** [comment]
Note that the way it is implemented now we avoid redundant error calculations.

**Comment by j-ostmeyer** [comment]
> Your pull request comes from your own fork. This means that I cannot push additional commits before merging it. It would be nicer if you just pushed this into a branch in this repository.

Just did so. See #221 .

**Pull request closed without merging**
