### PR TITLE
Remove rd files, next try

### PR DESCRIPTION
**Pull request by urbach**

### CODE REVIEW

**Comment by urbach** [comment]
NAMESPACE still to be generated by roxygen, too.

**Comment by j-ostmeyer** [comment]
> NAMESPACE still to be generated by roxygen, too.

Is that a long-time todo, or do you want to include it into this pull request?

**Comment by urbach** [comment]
> > NAMESPACE still to be generated by roxygen, too.
> 
> Is that a long-time todo, or do you want to include it into this pull request?

should be done now...

**Comment by urbach** [comment]
Is anyone having an idea how to automatise the inclusion of `@export` for all functions we export currently? It might be missing for some of the functions we originally documented using roxygen.
@kostrzewa @martin-ueding @j-ostmeyer

**Comment by martin-ueding** [comment]
There might be some false-positives and false-negatives still, but I believe that we are missing `@export` for these functions here:

- `*.raw_cf`
- `+.raw_cf`
- `-.raw_cf`
- `/.raw_cf`
- `add.raw_cf`
- `addStat.raw_cf`
- `block.raw_cf`
- `bootstrap.hankel`
- `bootstrap.meanerror`
- `c.raw_cf`
- `concat.raw_cf`
- `disc_3pt`
- `effectivemass`
- `effmass`
- `effmass2`
- `extract_mass`
- `extract_mass.effectivemassfit`
- `extract_mass.matrixfit`
- `foldr1`
- `g1`
- `get_plotdata_raw_cf`
- `getorderedconfignumbers`
- `hankel2cf`
- `hankel2effectivemass`
- `has_icf`
- `idx_matrix.raw_cf`
- `int_idx_matrix.raw_cf`
- `is.raw_cf`
- `is_empty.cf`
- `is_empty.raw_cf`
- `jab.cf`
- `jab.cf.derived`
- `loop_vev_subtract`
- `mul.raw_cf`
- `pcacfit`
- `plot.averx`
- `plot.b1fit`
- `plot.cfit`
- `plot.coshfit`
- `plot.effectivemass`
- `plot.effmass`
- `plot.gevp.amplitude`
- `plot.hadronacf`
- `plot.massfit`
- `plot.matrixfit`
- `plot.ofit`
- `plot.pionff`
- `plot.pionfit`
- `plot.raw_cf`
- `plot.rhofit`
- `plot_eigenvalue_timeseries`
- `plot_timeseries`
- `plothlinewitherror`
- `print.averx`
- `print.bootstrapfit`
- `print.effectivemassfit`
- `print.ofit`
- `print.pionfit`
- `print.raw_cf`
- `proton`
- `read_nissa_textcf_kernel`
- `readcmicor`
- `readcmidatafiles`
- `readcmiloopfiles`
- `readhlcor`
- `readnissatextcf`
- `removeTemporal.cf`
- `residual_plot`
- `residual_plot.bootstrapfit`
- `string2error`
- `subtract.excitedstates`
- `summary.averx`
- `summary.coshfit`
- `summary.effectivemass`
- `summary.effectivemassfit`
- `summary.gevp.amplitude`
- `summary.hadronacf`
- `summary.matrixfit`
- `summary.ofit`
- `summary.pionff`
- `summary.pionfit`
- `summary.raw_cf`
- `summary.uwerr`
- `uwerr.raw_cf`
- `uwerrderived`
- `uwerrprimary`
- `weight.cf`
- `weight_shift_reweight.cf`

These have been exported via the manual `NAMESPACE` but do not appear in the one generated.

**Comment by martin-ueding** [comment]
I'm adding a couple of them right now.

**Comment by martin-ueding** [comment]
The `@examples` must be last, so the `@export` needs to be before that.

**Comment by martin-ueding** [comment]
I have now added the `@export` to all the ones in the list, I believe that we now have the same exports as before.

**Comment by urbach** [comment]
> I have now added the `@export` to all the ones in the list, I believe that we now have the same exports as before.

Just that travis fails because there is no NAMESPACE file... :(

**Comment by martin-ueding** [comment]
Now the `NAMESPACE` file is available, but it fails somewhere else:

```
--- re-building ‘hankel.Rmd’ using rmarkdown
!!! Error: Ghostscript exited with error code 127!
Warning in system2(cmd, args = args, stdout = if (quiet) FALSE else "") :
  error in running command
Quitting from lines 114-115 (hankel.Rmd) 
Error: processing vignette 'hankel.Rmd' failed with diagnostics:
"invcosh" not resolved from current namespace (hadron)
--- failed re-building ‘hankel.Rmd’
```

That is a function via Rcpp, so likely we are missing somewhere too. It occured even before I removed the `src/RcppExports.cpp` from git.

**Pull request merged**
